foodName = input("Name a food > ")
plantName = input("Name a type of plant > ")
cookingMethod = input("Name a method of cooking > ")
burnedFood = input("What word describes burned food? > ")
diyItem = input("Name a DIY item > ")
print("")
print("MENU")
print("")
print(cookingMethod ,foodName, "with", burnedFood, plantName, "on a bed of", diyItem)